spring.application.name=TouristGuide
spring.sql.init.mode=never
spring.profiles.active=prod
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
